# Generated by Django 3.1.3 on 2020-11-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('content_type', 'object_id', 'user')},
        ),
    ]
