# Generated by Django 3.1.3 on 2020-11-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201116_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='111.jpg', upload_to='static/img/'),
        ),
    ]
