# Generated by Django 3.1.3 on 2020-12-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201201_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_imgs/avatar/200.jpeg', upload_to='default_imgs/avatar/', verbose_name='Аватарка'),
        ),
    ]
