# Generated by Django 3.1.3 on 2020-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201215_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_imgs/avatar/200.jpeg', upload_to='avatar/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
